function H_3x3 = computeHomography(src_pts_nx2, dest_pts_nx2)
    %src_pts_nx2  = [xs1 ys1; xs2 ys2; xs3 ys3; xs4 ys4];
    %dest_pts_nx2 = [xd1 yd1; xd2 yd2; xd3 yd3; xd4 yd4];
    A = [];
    for i = 1:4
        row_1 = [src_pts_nx2(i,1), src_pts_nx2(i,2), 1,...
            0, 0, 0,...
            -dest_pts_nx2(i,1)*src_pts_nx2(i,1),...
            -dest_pts_nx2(i,1)*src_pts_nx2(i,2),...
            -dest_pts_nx2(i,1)];
        row_2 = [0, 0, 0,... 
            src_pts_nx2(i,1), src_pts_nx2(i,2), 1,...
            -dest_pts_nx2(i,2)*src_pts_nx2(i,1),...
            -dest_pts_nx2(i,2)*src_pts_nx2(i,2),...
            -dest_pts_nx2(i,2)];
        A = [A; row_1; row_2];
    end
    [V, ~] = eig(A'*A);
    eigenvalues = eig(A'*A);
    [~, col] = min(eigenvalues);
    H_3x3 = [V(1,col), V(2,col), V(3,col);...
        V(4,col), V(5,col), V(6,col);...
        V(7,col), V(8,col), V(9,col)];
end

